name = "CircleFit"
uuid = "a2741ea9-3318-4d4b-8b99-ae5c58b57db7"
authors = ["Michael Pusterhofer <pusterhofer@student.tugraz.at>"]
version = "0.2.4"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LsqFit = "2fda8390-95c7-5789-9bda-21331edee243"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"

[compat]

LsqFit = "0.12, 0.13"
Roots = "2.0"
StatsBase = "0.33, 0.34"
julia = "1.6"
